#!/usr/bin/env bash
# This script displays a list of all running processes with STARTED time (including seconds) and shows hierarchy
ps -eo user,lstart,cmd --sort=start_time | awk 'BEGIN {printf "%-8s %-10s %s\n", "USER", "STARTED", "CMD"} NR>1 {printf "%-8s %-10s %s\n", $1, $4":"$5":"$6, substr($0, index($0,$8))}'
